apiVersion: v1
kind: Service

metadata:
  name: churn-backend-service
  namespace: churn-app

spec:
  type: NodePort

  selector:
    app: churn-backend

  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30465