apiVersion: apps/v1
kind: Deployment

metadata:
  name: churn-backend
  namespace: churn-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: churn-backend

  template:
    metadata:
      labels:
        app: churn-backend

    spec:
      containers:
        - name: churn-backend
          image: shre51/churn-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000