apiVersion: v1
kind: Service

metadata:
  name: churn-backend-service
  namespace: churn-app

spec:
  selector:
    app: churn-backend

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: NodePort  